-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Object.Brew exposing (abv, brewNumber, ibu, id, image, name, style)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import WeightyBeer.InputObject
import WeightyBeer.Interface
import WeightyBeer.Object
import WeightyBeer.Scalar
import WeightyBeer.ScalarCodecs
import WeightyBeer.Union


id : SelectionSet String WeightyBeer.Object.Brew
id =
    Object.selectionForField "String" "id" [] Decode.string


brewNumber : SelectionSet Float WeightyBeer.Object.Brew
brewNumber =
    Object.selectionForField "Float" "brewNumber" [] Decode.float


name : SelectionSet String WeightyBeer.Object.Brew
name =
    Object.selectionForField "String" "name" [] Decode.string


style : SelectionSet String WeightyBeer.Object.Brew
style =
    Object.selectionForField "String" "style" [] Decode.string


ibu : SelectionSet Float WeightyBeer.Object.Brew
ibu =
    Object.selectionForField "Float" "ibu" [] Decode.float


abv : SelectionSet Float WeightyBeer.Object.Brew
abv =
    Object.selectionForField "Float" "abv" [] Decode.float


image : SelectionSet decodesTo WeightyBeer.Object.Image -> SelectionSet (Maybe decodesTo) WeightyBeer.Object.Brew
image object_ =
    Object.selectionForCompositeField "image" [] object_ (identity >> Decode.nullable)
