-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Object.ImageMutation exposing (RemoveRequiredArguments, remove)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import WeightyBeer.InputObject
import WeightyBeer.Interface
import WeightyBeer.Object
import WeightyBeer.Scalar
import WeightyBeer.ScalarCodecs
import WeightyBeer.Union


type alias RemoveRequiredArguments =
    { id : String }


remove : RemoveRequiredArguments -> SelectionSet decodesTo WeightyBeer.Object.Image -> SelectionSet (Maybe decodesTo) WeightyBeer.Object.ImageMutation
remove requiredArgs object_ =
    Object.selectionForCompositeField "remove" [ Argument.required "id" requiredArgs.id Encode.string ] object_ (identity >> Decode.nullable)
