-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Object.Tap exposing (brew, id, isActive, name, order, volume, weight)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import WeightyBeer.InputObject
import WeightyBeer.Interface
import WeightyBeer.Object
import WeightyBeer.Scalar
import WeightyBeer.ScalarCodecs
import WeightyBeer.Union


id : SelectionSet String WeightyBeer.Object.Tap
id =
    Object.selectionForField "String" "id" [] Decode.string


name : SelectionSet String WeightyBeer.Object.Tap
name =
    Object.selectionForField "String" "name" [] Decode.string


order : SelectionSet Int WeightyBeer.Object.Tap
order =
    Object.selectionForField "Int" "order" [] Decode.int


volume : SelectionSet Float WeightyBeer.Object.Tap
volume =
    Object.selectionForField "Float" "volume" [] Decode.float


isActive : SelectionSet Bool WeightyBeer.Object.Tap
isActive =
    Object.selectionForField "Bool" "isActive" [] Decode.bool


brew : SelectionSet decodesTo WeightyBeer.Object.Brew -> SelectionSet (Maybe decodesTo) WeightyBeer.Object.Tap
brew object_ =
    Object.selectionForCompositeField "brew" [] object_ (identity >> Decode.nullable)


weight : SelectionSet decodesTo WeightyBeer.Object.Weight -> SelectionSet (Maybe decodesTo) WeightyBeer.Object.Tap
weight object_ =
    Object.selectionForCompositeField "weight" [] object_ (identity >> Decode.nullable)
