-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Object.WeightMutation exposing (CalibrateRequiredArguments, CustomCalibrationRequiredArguments, calibrate, customCalibration)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import WeightyBeer.InputObject
import WeightyBeer.Interface
import WeightyBeer.Object
import WeightyBeer.Scalar
import WeightyBeer.ScalarCodecs
import WeightyBeer.Union


type alias CalibrateRequiredArguments =
    { id : String
    , target : String
    }


calibrate : CalibrateRequiredArguments -> SelectionSet String WeightyBeer.Object.WeightMutation
calibrate requiredArgs =
    Object.selectionForField "String" "calibrate" [ Argument.required "id" requiredArgs.id Encode.string, Argument.required "target" requiredArgs.target Encode.string ] Decode.string


type alias CustomCalibrationRequiredArguments =
    { id : String
    , target : String
    , value : Float
    }


customCalibration : CustomCalibrationRequiredArguments -> SelectionSet String WeightyBeer.Object.WeightMutation
customCalibration requiredArgs =
    Object.selectionForField "String" "customCalibration" [ Argument.required "id" requiredArgs.id Encode.string, Argument.required "target" requiredArgs.target Encode.string, Argument.required "value" requiredArgs.value Encode.float ] Decode.string
