-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Object.Weight exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import WeightyBeer.InputObject
import WeightyBeer.Interface
import WeightyBeer.Object
import WeightyBeer.Scalar
import WeightyBeer.ScalarCodecs
import WeightyBeer.Union


id : SelectionSet String WeightyBeer.Object.Weight
id =
    Object.selectionForField "String" "id" [] Decode.string


zero : SelectionSet (Maybe Int) WeightyBeer.Object.Weight
zero =
    Object.selectionForField "(Maybe Int)" "zero" [] (Decode.int |> Decode.nullable)


empty : SelectionSet (Maybe Int) WeightyBeer.Object.Weight
empty =
    Object.selectionForField "(Maybe Int)" "empty" [] (Decode.int |> Decode.nullable)


full : SelectionSet (Maybe Int) WeightyBeer.Object.Weight
full =
    Object.selectionForField "(Maybe Int)" "full" [] (Decode.int |> Decode.nullable)


current : SelectionSet Int WeightyBeer.Object.Weight
current =
    Object.selectionForField "Int" "current" [] Decode.int


percent : SelectionSet Int WeightyBeer.Object.Weight
percent =
    Object.selectionForField "Int" "percent" [] Decode.int
