-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import WeightyBeer.InputObject
import WeightyBeer.Interface
import WeightyBeer.Object
import WeightyBeer.Scalar
import WeightyBeer.ScalarCodecs
import WeightyBeer.Union


image : SelectionSet decodesTo WeightyBeer.Object.ImageMutation -> SelectionSet decodesTo RootMutation
image object_ =
    Object.selectionForCompositeField "image" [] object_ identity


brew : SelectionSet decodesTo WeightyBeer.Object.BrewMutation -> SelectionSet decodesTo RootMutation
brew object_ =
    Object.selectionForCompositeField "brew" [] object_ identity


tap : SelectionSet decodesTo WeightyBeer.Object.TapMutation -> SelectionSet decodesTo RootMutation
tap object_ =
    Object.selectionForCompositeField "tap" [] object_ identity


weight : SelectionSet decodesTo WeightyBeer.Object.WeightMutation -> SelectionSet decodesTo RootMutation
weight object_ =
    Object.selectionForCompositeField "weight" [] object_ identity
