-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Mutation exposing (brew, image, tap)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import WeightyBeer.InputObject
import WeightyBeer.Interface
import WeightyBeer.Object
import WeightyBeer.Scalar
import WeightyBeer.ScalarCodecs
import WeightyBeer.Union


image : SelectionSet decodesTo WeightyBeer.Object.ImageMutation -> SelectionSet (Maybe decodesTo) RootMutation
image object_ =
    Object.selectionForCompositeField "image" [] object_ (identity >> Decode.nullable)


brew : SelectionSet decodesTo WeightyBeer.Object.BrewMutation -> SelectionSet (Maybe decodesTo) RootMutation
brew object_ =
    Object.selectionForCompositeField "brew" [] object_ (identity >> Decode.nullable)


tap : SelectionSet decodesTo WeightyBeer.Object.TapMutation -> SelectionSet (Maybe decodesTo) RootMutation
tap object_ =
    Object.selectionForCompositeField "tap" [] object_ (identity >> Decode.nullable)
