-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module WeightyBeer.Object exposing (Brew(..), BrewMutation(..), Image(..), ImageMutation(..), Tap(..), TapMutation(..), Weight(..), WeightMutation(..))


type Brew
    = Brew


type BrewMutation
    = BrewMutation


type Image
    = Image


type ImageMutation
    = ImageMutation


type Tap
    = Tap


type TapMutation
    = TapMutation


type Weight
    = Weight


type WeightMutation
    = WeightMutation
